### ISSUE TITLE
Twitch PubSub replacement

### ISSUE THREAD

**Issue by katasuno** [LeaPhant/pagkibot#7]
Can we use another API instead of Twitch PubSub? If we do, can we remove the 500 followers limit?

**Comment by LeaPhant** [comment]
Any existing twitch discord bot can be used instead for that purpose, this project was made specifically to use PubSub for instant notifications and updates compared to the 5+ minutes of delay with the regular API. You'll have to either use another bot or create a fork as it's not within the project's scope
